Added lease pages and the updated the loan fetching from the API usin…
DFE-Digital/Dfe.Academies.External pull request #160
Opened 2022-10-14 14:51 UTC by jarednimble

…g the new endpoints

Resolves #<1234>

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Expected behaviour

You should be able to use the loan and leases sections of the finance details page for an application

The leases pages have been added

The loan and lease creation/update/deletion uses new endpoints on the academisation API, these should be tested.

## Steps to reproduce issue (if relevant)

1. 
2.
3.
4.

## Steps to test this PR

1. Go to the finance review page
2. Add/Update/Delete loans and leases
3. See if the details are reflected in the database
4. Check the details are reflected on the review page

## Prerequisites

2022-10-14 15:03 UTC, paullocknimble approved these changes

2022-10-17 07:04 UTC, MarkRobinsonDfe requested changes
spotted 1 blooper maybe

2022-10-17 07:04 UTC, MarkRobinsonDfe commented on Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml.cs
> +				Status = selectedSchool.Loans != null ? SchoolConversionComponentStatus.Complete : SchoolConversionComponentStatus.NotStarted
shouldn;t this be selectedschool.leases?

2022-10-17 09:25 UTC, MarkRobinsonDfe approved these changes

2022-10-17 09:40 UTC, merged