AB#95250 Landing Page - add figma link to spec
DFE-Digital/Dfe.Academies.External pull request #20
Opened 2022-06-22 08:37 UTC by wystanpalm-madetech

Added Figma link to spec

2022-06-22 13:37 UTC, dhomerDFE requested changes
- There's a slight difference in the top paragraph. Should read:

"This form is for local authority maintained schools that want to convert to academy status."

- Can you remove the "You can save your work..." line. 
- The second to last bullet should include the "your" as part of the link.
- The link seems to be missing from the last bullet. 

Thanks

2022-06-24 10:04 UTC, mokoruwaDfE approved these changes

2022-06-24 10:04 UTC, mokoruwaDfE approved these changes

2022-06-24 10:08 UTC, mokoruwaDfE approved these changes

2022-06-24 11:42 UTC, dhomerDFE approved these changes

2022-06-24 11:44 UTC, merged