c# converts endpoint to a URI. So needs to be a valid URI
DFE-Digital/Dfe.Academies.External pull request #37
Opened 2022-07-11 11:56 UTC by MarkRobinsonDfe

Bug Fix
c# converts endpoint setting value to a URI. So needs to be a valid URI in settings

2022-07-12 14:05 UTC, wystanpalm-madetech requested changes

2022-07-12 14:26 UTC, MarkRobinsonDfe commented on Dfe.Academies.External.Web/appsettings.json
> +    "api_endpoint": "https://webapp-t1dv-sip-a2c.azurewebsites.net/",
c# converts endpoint setting value to a URI. So needs to be a valid URI in settings

2022-07-12 14:27 UTC, MarkRobinsonDfe commented on Dfe.Academies.External.Web/appsettings.json
> +    "api_endpoint": "https://webapp-t1dv-sip-a2c.azurewebsites.net/",
or, settings deployed to test URL @wystanpalm-madetech

2022-07-14 09:09 UTC, wystanpalm-madetech requested changes
Something weird has happened with the commits on this branch, can we tidy it up before merging?

2022-07-14 09:38 UTC, wystanpalm-madetech approved these changes

2022-07-14 09:40 UTC, merged